using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Security.Cryptography;
using System.Text;

namespace YourApp.Controllers
{
    [ApiController]
    [Route("api/[controller]")]
    public class EmployeesController : ControllerBase
    {
        private readonly AppDbContext _context;

        public EmployeesController(AppDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployee([FromBody] Employee request)
        {
            if (string.IsNullOrEmpty(request.Name) || string.IsNullOrEmpty(request.Email))
                return BadRequest("Name and Email are required");

            // Default password "employee" hashed
            string passwordHash = HashPassword("employee");

            var newEmployee = new Employee
            {
                Name = request.Name,
                Email = request.Email,
                Department = request.Department,
                PasswordHash = passwordHash
            };

            _context.Employees.Add(newEmployee);
            await _context.SaveChangesAsync();

            // newEmployee.Id is now auto-generated by the database
            return Ok(new { message = "Employee added successfully", employeeId = newEmployee.Id });
        }
        [HttpGet]
        public async Task<IActionResult> GetEmployees()
        {
            var employees = await _context.Employees.ToListAsync();
            return Ok(employees);
        }


        private string HashPassword(string password)
        {
            using var sha256 = SHA256.Create();
            byte[] bytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(password));
            return Convert.ToBase64String(bytes);
        }
    }
}
